sonar.projectKey=protocol-genesis
sonar.organization=protocol-genesis-org
sonar.projectName=Protocol Genesis - Backend
sonar.sourceEncoding=UTF-8

# איפה הקוד?
sonar.sources=.

# מציין שזה פרויקט פייתון
sonar.python.version=3.11
